# Generated by Django 3.2.11 on 2022-02-03 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0003_alter_publicchatroom_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicroomchatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
