# Generated by Django 3.2.11 on 2022-02-03 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0004_alter_publicroomchatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicroomchatmessage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 11, 53, 34, 348334, tzinfo=utc)),
        ),
    ]
