# Generated by Django 3.2.11 on 2022-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0006_alter_publicroomchatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicroomchatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
