# Generated by Django 3.2.11 on 2022-03-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelayBoardPinout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Relay Board Pinout', max_length=255, unique=True)),
                ('pump_pin', models.IntegerField(default=23)),
                ('mains_pin', models.IntegerField(default=24)),
                ('byp_pin', models.IntegerField(default=18)),
            ],
            options={
                'verbose_name_plural': 'Relay board pinout',
            },
        ),
    ]
