# Generated by Django 3.2.11 on 2022-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relayboardpinout',
            name='byp_pin',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='relayboardpinout',
            name='mains_pin',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='relayboardpinout',
            name='pump_pin',
            field=models.IntegerField(default=16),
        ),
    ]
