# Generated by Django 3.2.11 on 2022-04-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay_control', '0002_auto_20220301_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayBoardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Relay Board Status', max_length=255, unique=True)),
                ('pump_pin', models.BooleanField(default=False)),
                ('mains_pin', models.BooleanField(default=False)),
                ('byp_pin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Relay board status',
            },
        ),
    ]
