# Generated by Django 3.2.11 on 2022-04-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relay_control', '0003_relayboardstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relayboardstatus',
            old_name='byp_pin',
            new_name='byp_pin_state',
        ),
        migrations.RenameField(
            model_name='relayboardstatus',
            old_name='mains_pin',
            new_name='mains_pin_state',
        ),
        migrations.RenameField(
            model_name='relayboardstatus',
            old_name='pump_pin',
            new_name='pump_pin_state',
        ),
    ]
