# Generated by Django 3.2.11 on 2022-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_size', models.IntegerField(default=11)),
                ('sample_wait', models.DecimalField(decimal_places=1, default=0.1, max_digits=5)),
                ('temperature', models.IntegerField(default=20)),
                ('measurements_interval', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='SonarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_pin', models.IntegerField(default=23)),
                ('echo_pin', models.IntegerField(default=24)),
                ('failsafe_pin', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='TankLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('failsafe_engaged', models.BooleanField(default=False)),
            ],
        ),
    ]
