# Generated by Django 3.2.11 on 2022-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementsettings',
            name='title',
            field=models.CharField(default='Measurement Settings', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='sonarsettings',
            name='title',
            field=models.CharField(default='Sonar Settings', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tanklevel',
            name='title',
            field=models.CharField(default='Measurement Settings', max_length=255, unique=True),
        ),
    ]
