# Generated by Django 3.2.11 on 2022-01-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank_level', '0002_auto_20220131_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementsettings',
            options={'verbose_name_plural': 'Measurement settings'},
        ),
        migrations.AlterModelOptions(
            name='sonarsettings',
            options={'verbose_name_plural': 'Sonar settings'},
        ),
    ]
