# Generated by Django 3.2.11 on 2022-01-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tank_level', '0003_auto_20220131_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanklevel',
            name='title',
        ),
    ]
