# Generated by Django 3.2.11 on 2022-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_level', '0004_remove_tanklevel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tank Size', max_length=255, unique=True)),
                ('length', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
                ('width', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Tank Size',
            },
        ),
    ]
