# Generated by Django 3.2.11 on 2022-02-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_level', '0006_auto_20220206_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanklevel',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
