# Generated by Django 3.2.11 on 2022-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_level', '0007_tanklevel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanklevel',
            name='distance',
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tanklevel',
            name='volume_m3',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=10),
        ),
    ]
