# Generated by Django 3.2.11 on 2022-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleMeasurementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sample Measurement Settings', max_length=255, unique=True)),
                ('sample_size', models.IntegerField(default=11)),
                ('sample_wait', models.DecimalField(decimal_places=1, default=0.1, max_digits=5)),
                ('temperature', models.IntegerField(default=20)),
                ('measurements_interval', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Sample measurement settings',
            },
        ),
        migrations.CreateModel(
            name='SonarPinout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sonar Pinout', max_length=255, unique=True)),
                ('trigger_pin', models.IntegerField(default=23)),
                ('echo_pin', models.IntegerField(default=24)),
                ('failsafe_pin', models.IntegerField(default=18)),
            ],
            options={
                'verbose_name_plural': 'Sonar pinout',
            },
        ),
        migrations.CreateModel(
            name='TankSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tank Size', max_length=255, unique=True)),
                ('length', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
                ('width', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=1, default=100.0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Tank size',
            },
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=1, default=-1.0, max_digits=10)),
                ('volume_m3', models.DecimalField(decimal_places=2, default=-1.0, max_digits=10)),
                ('volume_l', models.DecimalField(decimal_places=1, default=-1.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('failsafe_engaged', models.BooleanField(default=False)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
