# Generated by Django 3.2.11 on 2022-02-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_level', '0002_auto_20220225_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementsinterval',
            name='measurements_interval',
        ),
    ]
