# Generated by Django 3.2.11 on 2022-03-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_level', '0003_remove_measurementsinterval_measurements_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterlevel',
            old_name='failsafe_engaged',
            new_name='failsafe_status',
        ),
        migrations.RenameField(
            model_name='waterlevel',
            old_name='status',
            new_name='status_message',
        ),
        migrations.RenameField(
            model_name='waterlevel',
            old_name='distance',
            new_name='water_level',
        ),
    ]
