# Generated by Django 3.2.11 on 2022-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_level', '0005_remove_samplemeasurement_measurements_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonarpinout',
            name='trigger_pin',
            field=models.IntegerField(default=23, verbose_name='Trigger pin (GPIO Numbering)'),
        ),
    ]
