# Generated by Django 3.2.11 on 2022-03-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_level', '0006_alter_sonarpinout_trigger_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsinterval',
            name='interval',
            field=models.IntegerField(default=10, verbose_name='Measurement Interval (seconds)'),
        ),
        migrations.AlterField(
            model_name='samplemeasurement',
            name='sample_size',
            field=models.IntegerField(default=11, verbose_name='Sample size (Avg of this many single measurements)'),
        ),
        migrations.AlterField(
            model_name='samplemeasurement',
            name='sample_wait',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=5, verbose_name='Sample Wait (seconds)'),
        ),
        migrations.AlterField(
            model_name='samplemeasurement',
            name='temperature',
            field=models.IntegerField(default=20, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='sonarpinout',
            name='echo_pin',
            field=models.IntegerField(default=24, verbose_name='Echo pin (GPIO Number)'),
        ),
        migrations.AlterField(
            model_name='sonarpinout',
            name='failsafe_pin',
            field=models.IntegerField(default=18, verbose_name='Failsafe pin (GPIO Number)'),
        ),
        migrations.AlterField(
            model_name='sonarpinout',
            name='trigger_pin',
            field=models.IntegerField(default=23, verbose_name='Trigger pin (GPIO Number)'),
        ),
        migrations.AlterField(
            model_name='tanksize',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=5, verbose_name='Tank Depth (cm)'),
        ),
        migrations.AlterField(
            model_name='tanksize',
            name='length',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=5, verbose_name='Tank Length (cm)'),
        ),
        migrations.AlterField(
            model_name='tanksize',
            name='width',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=5, verbose_name='Tank Width (cm)'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='volume_l',
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=10, verbose_name='Water Volume (liters)'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='volume_m3',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=10, verbose_name='Water Volume (m³)'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='water_level',
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=10, verbose_name='To Water Level (cm)'),
        ),
    ]
