# Generated by Django 3.2.11 on 2022-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_level', '0007_auto_20220303_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevel',
            name='volume_l',
            field=models.IntegerField(default=-1, verbose_name='Water Volume (liters)'),
        ),
    ]
